### ISSUE TITLE
sewergraph conda environment - fiona dependencies

### ISSUE THREAD

**Issue by nworbc5565** [aerispaha/trace#7]
Hey @aerispaha , 

Working off a conda environment you had created <sewergraph>, assuming it was for this project. Not sure how much you've updated packages in this environment since switching computers. However, when trying to run the notebook from yesterday straight from the command line, I started having issues with fiona. 

Geopandas wasn't installed (acheived using conda install -c conda-forge geopandas in the sewergraph env).
Then, I received an ImportError from Fiona (see PNG). Tried reinstalling fiona and other geopandas dependencies in case there needed to an update (via instructions here http://geopandas.org/install.html), with no luck. Ever have this issue before?

![fiona error](https://user-images.githubusercontent.com/22076991/34442638-747acb92-ec91-11e7-9c26-66c15b7e9f16.png)

Thanks - CB

**Comment by aerispaha** [comment]
Hey @nworbc5565, oof... 

So I'm sure why your having issues with that environment. But I do know that running `conda install -c conda-forge geopandas` never worked properly. I think this stems from ArcMap taking over the computer when it get installed.

The way I've gotten it to work on any machine with acrpy installed is by following [this process](http://geoffboeing.com/2014/09/using-geopandas-windows/), starting from where it says "**Installing geopandas and its dependencies manually**". You have to download the "wheels" for each package individually and `pip install` them. Because that sewergraph env may now be on the fritz, I'd recommend starting with a fresh environment. Overall, I'd try this process: 

1. Create a new virtual environment: `conda create -n mynewenv`
2. activate that environment: `activate mynewenv`
3. Download the wheels per step one
4. `pip install` each wheel in the order Geoff Boeing recommends

I would then go to wherever you have the sewergraph source and run `python setup.py develop`, while in the new virtual environment.

**Comment by aerispaha** [comment]
Moving this convo to #11
